### PR TITLE
show an error if the user attempts to get >10000 incidents

### LINKED ISSUE #163: [Bug] - API error "Offset+limit exceeds maximum allowed value of 10000"
`incidents?limit=100&total=true&offset=95600...` and a "Since" date 2 months in the past

returns API error:
`Offset+limit exceeds maximum allowed value of 10000. Please try to refine your search to reduce the returned set of records below this number, like adding a date range`

### PR DESCRIPTION
**Pull request by martindstone**
to fix #163

### CODE REVIEW

**Review by gsreynolds — APPROVED** [review]
LGTM

File: src/redux/incidents/sagas.js [hunk 1]
```diff
@@ -136,6 +136,7 @@ export function* getIncidentsImpl() {
     incidents = yield call(pdParallelFetch, 'incidents', baseParams, null, {
       priority: 5,
       skipSort: true,
+      maxRecords: 10000,
```
Comment (gsreynolds) [inline src/redux/incidents/sagas.js:139]: @martindstone - Does this actually get used?

Looks like it's just looking at incidents error to detect too many incidents
```
 if (!fetchingIncidents && incidents.length === 0 && incidentsError?.startsWith('Too many records')) {
 ```

**Comment by gsreynolds** [comment]
Screenshot 2023-07-17 at 09 42 48
