### PR TITLE
Lazy loading plus UI & state fixes

### LINKED ISSUE #72: [Bug] - Reloading the incidents list causes downloaded notes and alerts to be refetched

### LINKED ISSUE #73: [Enhancement] - Implement lazy-loading of incident notes and alerts
The current behaviour causes significant UI performance issues when the number of filtered incidents is large

### LINKED ISSUE #74: [Enhancement] - Added a Detailed Status overlay
Currently difficult to understand the state of API requests. Add detailed status, available by clicking the status beacon, which shows the status of the app's API requests

### LINKED ISSUE #75: [Enhancement] - Changing filters should not cause the incidents list to be reloaded unless necessary

### LINKED ISSUE #76: [Enhancement] - Add "global" search to find results inside all alert fields, even if not displayed as columns

### LINKED ISSUE #77: [Enhancement] - Display key details of alerts such as summary, timestamp and status
Num Alerts column only shows the total count. Hovering on the column should show more details.

### PR DESCRIPTION
**Pull request by gsreynolds**
This PR introduces significant user experience and performance improvements, aimed at addressing the needs of the largest users of PD Live.

**Internal app changes:**

- Rewrote the app's internal state management to simplify and improve the storage of downloaded server state
- Simplified the processing of downloaded live updates
- Refactored and simplified UI components
- Improved the consistency of internal call rate limiting
- Removed extraneous code and API calls
- Implemented direct updating of incident state when actions are performed
- Implemented lazy-loading of incident notes and alerts driven by the user's interactions within the app. Closes #73 
- Rewrote the table column definition code to support future expansion
- Rewrote the filtering components and filter implementations to support future expansion

The above changes have the following effects:

- Reduced unnecessary API calls to refresh or refetch information that has already been downloaded (the app uses the API more efficiently and loads faster). 
- User interaction is not blocked while API calls are in flight
- Changing filters does not reload the incidents list unless it's necessary. Closes #75 
- Reloading the incidents list does not force already downloaded notes and alerts to be prefetched. Closes #72

**Bug fixes:**

- Multiple issues that could lead to cause exceptions and result in the app showing a "blank screen" were identified and resolved

**UI changes:**

- Simplified the Settings dialog and made it more user friendly
- Adopted a new User Interface framework with built-in Light Mode and Dark Mode support 
- Moved the Dark Mode toggle to the main navigation bar
- Rewrote the column selection dialog to improve the user experience and moved it to the main dropdown menu
- Added a Detailed Status overlay, available by clicking the status beacon, that shows the status of the app's API requests. Closes #74 
- Rewrote the Incident Merge component so that it:
	- allows merging of resolved incidents
	- defaults to the latest selected incident as the merge target
	- offers the option to prepend text to the merged incidents' titles indicating that they were merged with another incident
- Added a component that is shown when the user hovers over the Num Alerts column, that lists the alerts contained in an incident. Closes #77 
- Added functionality to search all custom alert details when using global search, to be able to find things like emf_id even if that value is not being displayed in a column. Closes #76 
	- This functionality has to be turned on, there is a switch in Settings (this is just for consistency with deployed app behavior, there is no performance impact)

### CODE REVIEW

File: src/config/fuse-config.js [hunk 1]
```diff
@@ -1,5 +1,6 @@
 // Configuration for Fuse.js (Fuzzy Search)
 
+// TODO: Use column-generator
```
Comment (gsreynolds) [inline src/config/fuse-config.js:3]: Need to import column-generator here, for availableIncidentTableColumns, availableAlertTableColumns,

File: src/config/incident-table-columns.js [hunk 2]
```diff
@@ -435,21 +435,33 @@ export const availableAlertTableColumns = [
   {
     columnType: 'alert',
     accessor: (incident) => {
-      let content;
```
Comment (gsreynolds) [inline src/config/incident-table-columns.js:438]: Need to fully remove incident table columns

**Review by gsreynolds — COMMENTED** [review]
Need a final pass on removing code that's been superseded by the new implementation

**Review by gsreynolds — COMMENTED** [review]
Need a final pass on removing code that's been superseded by the new implementation

File: src/redux/query_settings/sagas.js [hunk 3]
```diff
@@ -227,52 +318,57 @@ export function* validateIncidentQuery() {
...
+
+    // // Determine if Confirm Query Modal component should be rendered
+    // if (totalIncidentsFromQuery > maxIncidentsLimit && !autoAcceptIncidentsQuery) {
+    //   yield put({ type: TOGGLE_DISPLAY_CONFIRM_QUERY_MODAL_REQUESTED });
+    // } else {
+    //   yield put({ type: CONFIRM_INCIDENT_QUERY_REQUESTED, confirm: true });
+    // }
+    // yield put({
+    //   type: FILTER_INCIDENTS_LIST,
+    // });
```
Comment (gsreynolds) [inline src/redux/query_settings/sagas.js:371]: A lot of commented-out code here - is it superseded and needs removed? The skipped unit tests are checking a lot of this commented out behaviour
